require 'highline'
$terminal = HighLine.new
require 'commander/version'
require 'commander/blank'
require 'commander/user_interaction'
require 'commander/core_ext'
require 'commander/runner'
require 'commander/command'
require 'commander/help_formatters'
require 'commander/platform'
require 'commander/delegates'
require 'commander/methods'
require 'commander/configure'
